move_group:

  disable_capabilities: move_group/MoveGroupCartesianPathService
  capabilities: descartes_capability/MoveGroupDescartesPathService

  descartes_params:
    positional_tolerance: 0.001
    positional_tolerance_inc: 0.001
    roll_orientation_tolerance: 0.1
    pitch_orientation_tolerance: 0.1
    yaw_orientation_tolerance: 0.1
    orientation_tolerance_inc: 0.1

    debug:
      visual: true
      verbose: true
